import Stripe from 'stripe';
import { fail,authorize,audit,planFor,now } from './core.js';
export function testStripe(env){fail(/^sk_test_/.test(env.STRIPE_SECRET_KEY||''),503,'STRIPE_TEST_REQUIRED','Stripe TEST no configurado; claves LIVE rechazadas');return new Stripe(env.STRIPE_SECRET_KEY,{maxNetworkRetries:1,timeout:15000});}
export class Billing {
 constructor(store,env,client){this.store=store;this.env=env;this.client=client;}
 stripe(){return this.client||testStripe(this.env);}
 priceMap(){let map;try{map=JSON.parse(this.env.STRIPE_PRICE_MAP_JSON||'{}');}catch{fail(false,503,'PRICE_CONFIG','Mapa Stripe inválido');}return map;}
 async checkout(orgId,user,plan){fail(/^historical(19|49|149|299)$/.test(plan),400,'PLAN_INVALID','Plan de prueba inválido');const org=await this.store.get(orgId);authorize(org,user.uid,['owner']);const price=this.priceMap()[plan];fail(price,503,'PRICE_REQUIRED','Price TEST pendiente de configuración');const stripe=this.stripe();const verified=await stripe.prices.retrieve(price);fail(!verified.livemode&&verified.active&&verified.currency==='eur'&&verified.type==='recurring'&&verified.unit_amount===planFor(plan).historicalEUR*100,503,'PRICE_INVALID','Price incompatible con referencia histórica de prueba');
 let customerId=org.subscription.customerId;if(!customerId){const customer=await stripe.customers.create({email:user.email||undefined,metadata:{organizationId:orgId,firebaseUID:user.uid}},{idempotencyKey:`zenit-test-customer-${orgId}`});fail(!customer.livemode,503,'LIVE_REJECTED','Cliente LIVE rechazado');customerId=customer.id;await this.store.transaction(orgId,o=>{authorize(o,user.uid,['owner']);o.subscription.customerId=customerId;audit(o,user.uid,'billing.customer_linked',customerId);});}
 const session=await stripe.checkout.sessions.create({mode:'subscription',customer:customerId,line_items:[{price,quantity:1}],client_reference_id:orgId,metadata:{organizationId:orgId},subscription_data:{metadata:{organizationId:orgId}},success_url:`${this.env.APP_ORIGIN}/?billing=returned`,cancel_url:`${this.env.APP_ORIGIN}/?billing=cancelled`});return {url:session.url,mode:'test'};
 }
 async portal(orgId,user){const org=await this.store.get(orgId);authorize(org,user.uid,['owner']);fail(org.subscription.customerId,409,'CUSTOMER_REQUIRED','No existe cliente de prueba');return this.stripe().billingPortal.sessions.create({customer:org.subscription.customerId,return_url:this.env.APP_ORIGIN});}
 async webhook(raw,signature){fail(this.env.STRIPE_WEBHOOK_SECRET,503,'WEBHOOK_CONFIG','Falta secreto webhook');let event;try{event=this.stripe().webhooks.constructEvent(raw,signature,this.env.STRIPE_WEBHOOK_SECRET,300);}catch{fail(false,400,'WEBHOOK_SIGNATURE','Firma Stripe inválida');}return this.handle(event);}
 async handle(event){fail(event.livemode===false,400,'LIVE_REJECTED','Eventos LIVE rechazados');const object=event.data?.object;const customer=typeof object.customer==='string'?object.customer:object.customer?.id;if(!customer)return {ignored:true};const orgId=await this.store.findCustomer(customer);if(!orgId)return {ignored:true};const org=await this.store.get(orgId);if(org.billingEvents[event.id])return {duplicate:true};
 const types=['customer.subscription.created','customer.subscription.updated','customer.subscription.deleted','invoice.paid','invoice.payment_failed','charge.refunded','charge.dispute.created','charge.dispute.closed'];if(!types.includes(event.type))return {ignored:true};
 const isSub=event.type.startsWith('customer.subscription.');const subId=isSub?object.id:(object.parent?.subscription_details?.subscription||object.subscription||org.subscription.id);let sub=null,plan=null;
 if(subId){sub=await this.stripe().subscriptions.retrieve(subId);fail(sub.livemode===false&&sub.customer===customer&&sub.metadata?.organizationId===orgId,400,'SUBSCRIPTION_MAPPING','Suscripción no vinculada correctamente');const priceId=sub.items?.data?.[0]?.price?.id;plan=Object.entries(this.priceMap()).find(([,price])=>price===priceId)?.[0];fail(plan,400,'PRICE_UNKNOWN','Price no reconocido');}
 return this.store.transaction(orgId,o=>{if(o.billingEvents[event.id])return {duplicate:true};fail(Object.keys(o.billingEvents).length<500,409,'BILLING_CAPACITY','Archivado de eventos requerido');o.billingEvents[event.id]={type:event.type,created:event.created,processedAt:now()};
 if(event.type==='charge.refunded'||event.type==='charge.dispute.created'){o.subscription.billingHold=true;for(const c of Object.values(o.commissions))if(c.customerId===customer){c.status='held';c.reason=event.type;}}
 if(sub){o.subscription={...o.subscription,id:sub.id,status:o.subscription.billingHold?'review_required':sub.status,mode:'test',periodEnd:sub.items?.data?.[0]?.current_period_end||null,cancelAtPeriodEnd:sub.cancel_at_period_end};o.plan=plan;}
 if(event.type==='invoice.payment_failed'&&!o.subscription.billingHold&&sub?.status!=='active')o.subscription.status='past_due';
 if(event.type==='invoice.paid'&&object.paid===true&&!o.invoices[object.id]){o.invoices[object.id]={id:object.id,amountPaid:object.amount_paid,currency:object.currency,at:now(),mode:'test'};if(object.amount_paid>0&&!o.subscription.billingHold)o.creditBalance= Math.max(0,o.creditBalance)+planFor(plan).initialCredits;const referral=Object.values(o.referrals).find(r=>r.customerId===customer);if(referral)o.commissions[object.id]={id:object.id,invoiceId:object.id,customerId:customer,partnerId:referral.partnerId,rate:0.2,baseNet:null,amount:null,status:'pending_policy',mode:'test',note:'No se calcula ni paga hasta definir actividad, base neta y atribución'};}
 audit(o,'stripe','billing.event',event.id,{type:event.type});return {received:true};});
 }
}
